# Generated by Django 5.2.4 on 2025-08-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('campaign_start_date', models.DateField()),
                ('campaign_end_date', models.DateField()),
                ('exhibition_start_date', models.DateField(blank=True, null=True)),
                ('exhibition_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_volunteers', models.IntegerField(default=0)),
                ('max_volunteers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sections', to='core.campaign')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_campaigns', to='core.section')),
            ],
            options={
                'unique_together': {('campaign', 'section')},
            },
        ),
        migrations.CreateModel(
            name='CampaignVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_volunteers', to='core.campaign')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_campaigns', to='core.volunteer')),
            ],
            options={
                'unique_together': {('campaign', 'volunteer')},
            },
        ),
    ]
