# Generated by Django 5.2.4 on 2025-08-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_campaign_campaignsection_campaignvolunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.campaignsection')),
                ('campaign_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to='core.campaignvolunteer')),
            ],
            options={
                'unique_together': {('campaign_volunteer', 'campaign_section')},
            },
        ),
    ]
